In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

In [2]:
df = pd.read_csv("../data/processed/train_cleaned.csv",
parse_dates=['Order Date', 'Ship Date']
)

In [3]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Shipping Days
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,3
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,7
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,7

### --Order Year

1. Which year generated highest sales?

In [4]:
df['Order Year'] = df['Order Date'].dt.year

In [8]:
df[['Order Date', 'Order Year']].head()

  Order Date  Order Year
0 2017-11-08        2017
1 2017-11-08        2017
2 2017-06-12        2017
3 2016-10-11        2016
4 2016-10-11        2016

### Order Month 

2. Which month generates highest sales?

In [9]:
df['Order Month'] = df['Order Date'].dt.month_name()

In [10]:
df[['Order Month', 'Order Date']].head()

  Order Month Order Date
0    November 2017-11-08
1    November 2017-11-08
2        June 2017-06-12
3     October 2016-10-11
4     October 2016-10-11

### Order Quater

3. Which quater perform best??

In [11]:
df['Order Quarter'] = (
    'Q'  +
    df['Order Date'].dt.quarter.astype(str) 
)

In [12]:
df[['Order Date','Order Quarter']].head()

  Order Date Order Quarter
0 2017-11-08            Q4
1 2017-11-08            Q4
2 2017-06-12            Q2
3 2016-10-11            Q4
4 2016-10-11            Q4

### Shipping Speed Category

4. How many orders are Fast, Standard, or Slow?

In [14]:
df['Shipping Speed']= np.where(
    df['Shipping Days'] <= 2,
    'Fast',
    np.where(
        df['Shipping Days'] <= 5,
        'Standard',
        'Slow'
    )
)

In [15]:
df[['Shipping Days','Shipping Speed']].head()

   Shipping Days Shipping Speed
0              3       Standard
1              3       Standard
2              4       Standard
3              7           Slow
4              7           Slow

### Sales Category

5. How many low-value and high-value orders exist?

In [16]:
df['Sales Category'] = pd.cut(
    df['Sales'],
    bins=[0,100,500, 5000, 25000],
    labels=[
        'Low',
        'Medium',
        'High',
        'Permium'
    ]
)

In [17]:
df[['Sales','Sales Category']].head()

      Sales Sales Category
0  261.9600         Medium
1  731.9400           High
2   14.6200            Low
3  957.5775           High
4   22.3680            Low


### Customer Order Count

6.Who are repeat customers?

In [19]:
customer_orders = (
    df.groupby('Customer ID')['Order ID']
    .nunique()
)

df['Customer Order Count'] = (
    df['Customer ID']
    .map(customer_orders)

)

### Customer Type

In [20]:
df['Customer Type'] = np.where(
    df['Customer Order Count'] > 5,
    'Repeat Customer',
    'New Customer'
)

In [21]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Shipping Days,Order Year,Order Month,Order Quarter,Shipping Speed,Sales Category,Customer Order Count,Customer Type
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,3,2017,November,Q4,Standard,Medium,3,New Customer
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,2017,November,Q4,Standard,High,3,New Customer
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4,2017,June,Q2,Standard,Low,5,New Customer
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,7,2016,October,Q4,Slow,High,6,Repeat Customer
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,7,2016,October,Q4,Slow,Low,6,Repeat Customer

In [22]:
df.to_csv(
    '../data/processed/feature_engineered_sales.csv',
    index=False
)